spring:
  devtools:
    add-properties: true
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/blendsshop
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
cloud:
  aws:
    s3:
      url: https://s3.localhost.localstack.cloud:4566
      bucket-name: blends-shop-bucket
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: test
      secret-key: test
admin:
  access_code: teste
  secret: teste123
jwt:
  key: Qp3Hyp428oqrTRljnZquaabGVJV6IY150K6ugfOuBXWZN7BZslJjEHnAN6abzQXd