spring:
  devtools:
    add-properties: true
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/blendsshop
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

